#!/usr/bin/env python3
"""Builds app/minapp-skin.css: Webamp's built-in skin with the word WINAMP in its title bars replaced by MINAPP.

The word is re-assembled from the skin's own letters (M, I, N, A, P all occur in WINAMP), so the pixel font is
untouched. Usage:  python3 make-minapp-skin.py /path/to/webamp/built/webamp.bundle.js ../app/minapp-skin.css
Needs Pillow and numpy.
"""
import base64, io, re, sys
import numpy as np
from PIL import Image

bundle, out = sys.argv[1], sys.argv[2]
s = open(bundle, encoding='utf8').read()
i = s.index('var css_248z = "') + len('var css_248z = "')
j = i
while True:
    j = s.index('"', j)
    k, n = j - 1, 0
    while s[k] == '\\':
        n += 1; k -= 1
    if n % 2 == 0: break
    j += 1
css = s[i:j].replace('\\n', '\n').replace('\\"', '"').replace('\\\\', '\\')
rules = {}
for sel, body in re.findall(r'([^{}]+)\{([^{}]*)\}', css):
    rules.setdefault(' '.join(sel.split()), '')
    rules[' '.join(sel.split())] += body  # a selector can appear twice (size rule + image rule)

def sprite(selector):
    m = re.search(r'url\(data:image/png;base64,([A-Za-z0-9+/=]+)\)', rules[selector])
    return Image.open(io.BytesIO(base64.b64decode(m.group(1)))).convert('RGBA')

SPRITES = {  # name: (css selector, is the selected variant, how far the word is shifted right)
    'main':      '#webamp #title-bar',
    'main_sel':  '#webamp .selected #title-bar',
    'shade':     '#webamp .shade #title-bar',
    'shade_sel': '#webamp .shade.selected #title-bar',
    'eq':        '#webamp .equalizer-top',
    'eq_sel':    '#webamp .selected .equalizer-top',
    'pl':        '#webamp .playlist-top-title',
    'pl_sel':    '#webamp .selected .playlist-top-title',
}
imgs = {k: sprite(v) for k, v in SPRITES.items()}

# The word WINAMP as it sits in the main title bar: columns 118..156, rows 5..10 (selected variant)
ref = np.array(imgs['main_sel'].convert('RGB')).astype(int).sum(axis=2) // 3
TX0, TW = 118, 39
tmpl = ref[5:11, TX0:TX0 + TW] > 150

def find(img):
    a = np.array(img.convert('RGB')).astype(int).sum(axis=2) // 3
    best = (-1, 0, 0)
    for y in range(0, a.shape[0] - 6 + 1):
        for x in range(0, a.shape[1] - TW + 1):
            sc = ((a[y:y + 6, x:x + TW] > 150) == tmpl).mean()
            if sc > best[0]: best = (sc, x, y)
    return best

# letter columns inside the 39-wide word: W 0-7, I 9-10, N 12-17, A 18-23, M 25-31, P 33-38; gaps at 8, 11, 24, 32
def new_columns():
    cols = []
    cols += list(range(25, 32))      # M
    cols += [8]                       # gap
    cols += [9, 10]                   # I
    cols += [11]                      # gap
    cols += list(range(12, 18))      # N
    cols += list(range(18, 24))      # A
    cols += [24]                      # gap
    cols += list(range(33, 39))      # P
    cols += [32]                      # gap
    cols += list(range(33, 39))      # P
    return cols                       # 37 columns

def patch(img, x0, shift):
    src = img.copy(); dst = img.copy()
    cols = new_columns()
    for o in range(TW):
        c = o - shift
        s_off = cols[c] if 0 <= c < len(cols) else 8   # outside the word: plain background (a gap column)
        for y in range(img.height):
            dst.putpixel((x0 + o, y), src.getpixel((x0 + s_off, y)))
    return dst

pos = {}
for name in imgs:
    if name in ('main_sel', 'main'): pos[name] = (TX0, 5)
    elif name.startswith('shade'): pos[name] = (TX0 - 98, 5)
    elif name.endswith('_sel') or name in ('eq', 'pl'):
        pass
# find the word in the selected EQ / playlist sprites, reuse for the unselected ones
for base in ('eq', 'pl'):
    sc, x, y = find(imgs[base + '_sel'])
    assert sc > 0.9, (base, sc)
    pos[base + '_sel'] = pos[base] = (x, y)

def data_uri(im):
    b = io.BytesIO(); im.save(b, 'PNG'); return 'data:image/png;base64,' + base64.b64encode(b.getvalue()).decode()

lines = ['/* Generated by tools/make-minapp-skin.py: the default skin with MINAPP in the title bars. */']
for name, sel in SPRITES.items():
    x0 = pos[name][0]
    shift = 1 if name.startswith(('main', 'shade')) else 2
    new = patch(imgs[name], x0, shift)
    # only when the built-in skin is active (html.minapp-default is toggled by the renderer)
    lines.append(f'html.minapp-default {sel} {{ background-image: url({data_uri(new)}); }}')
    new.save(f'/tmp/minapp-{name}.png')
open(out, 'w').write('\n'.join(lines) + '\n')
print('wrote', out, {k: v for k, v in pos.items()})
