const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('bridge', {
  state: () => ipcRenderer.invoke('spotify:state'),
  cmd: (c, a) => ipcRenderer.invoke('spotify:cmd', c, a),
  size: (w, h) => ipcRenderer.send('win:size', w, h),
  dragStart: () => ipcRenderer.send('win:dragstart'),
  dragEnd: () => ipcRenderer.send('win:dragend'),
  capPrepare: (mode) => ipcRenderer.invoke('cap:prepare', mode),
  eqState: (s) => ipcRenderer.send('eq:state', s),
  prefsGet: () => ipcRenderer.invoke('prefs:get'),
  prefsSave: (u) => ipcRenderer.send('prefs:save', u),
  saveSkin: (name, buf) => ipcRenderer.invoke('skin:save', name, buf),
  log: (m) => ipcRenderer.send('app:log', m),
  eqMessage: (t) => ipcRenderer.send('eq:message', t),
  pinToggle: () => ipcRenderer.invoke('pin:toggle'),
  pinGet: () => ipcRenderer.invoke('pin:get'),
  onPin: (cb) => ipcRenderer.on('pin:state', (_e, v) => cb(v)),
  showMenu: () => ipcRenderer.send('menu:show'),
  onWindowToggle: (cb) => ipcRenderer.on('window:toggle', (_e, id) => cb(id)),
  quit: () => ipcRenderer.send('app:quit'),
  lastSkin: () => ipcRenderer.invoke('skin:last'),
  onSkin: (cb) => ipcRenderer.on('skin:load', (_e, buf) => cb(buf)),
  onMini: (cb) => ipcRenderer.on('mini:toggle', cb),
  onMilkdrop: (cb) => ipcRenderer.on('milkdrop:toggle', cb),
});
